---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: ~
  labels:
    app: minimal-spring-demo
  name: minimal-spring-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimal-spring-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: ~
      labels:
        app: minimal-spring-demo
    spec:
      containers:
        - image: "index.docker.io/benjvi/minimal-spring-web-demo@sha256:ef41b316f6f21f362ca014a1aa0c76c4955d3a24a12c5b02bc72f346b6360061"
          name: minimal-spring-demo
          resources: {}
          securityContext:
            runAsNonRoot: true
status: {}
