---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: ~
  labels:
    app: minimal-spring-demo
  name: minimal-spring-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimal-spring-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: ~
      labels:
        app: minimal-spring-demo
    spec:
      containers:
        - image: "index.docker.io/benjvi/minimal-spring-web-demo@sha256:ac68157a4c6580147ff1f694857f6caecccaf7be9f9b40d4ba6faea3056ded88"
          name: minimal-spring-demo
          resources: {}
          securityContext:
            runAsNonRoot: true
status: {}
