apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-demo-prod
  namespace: argo
  labels: null
  annotations: null
spec:
  destination:
    namespace: prod-spring-app
    server: https://34.76.1.180
  project: apps-gitops
  source:
    path: prod-cluster/spring-app
    repoURL: https://github.com/benjvi/apps-gitops
    targetRevision: HEAD
    kustomize: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
