name: Promote to prod

on:
  schedule:    
  - cron: "2 8,13 * * *"
  repository_dispatch:
    types:
      - "promote-to-prod" 

jobs:
  pipeline:
    environment: default
    runs-on:
    - ubuntu-latest
    steps:
      - name: Triggered by event
        if: github.event_name == 'repository_dispatch'
        run: 'echo "Triggered by: ${{ github.event.client_payload.user }}"'

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_REPO_PAT_TOKEN }}

      - name: Promote manifests
        with:
          entrypoint: '.github/scripts/copy-files.sh'
          args: 'nonprod-cluster/* prod-cluster'
        uses: docker://benjvi/prify:latest

      - name: Make PRs
        with:
          entrypoint: '.github/scripts/run-prify.sh'
          args: 'nonprod-cluster'
        uses: docker://benjvi/prify:latest

